name: Windows Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: npm install gui
      run: |
            cd gui\static
            npm install
            node node_modules/gulp/bin/gulp.js compile
            cd ..\..

    - name: Build
      env:
        PATH:
      run: |
        echo "::add-path::C:\\go\\bin"
        go run make.go -v Windows

    - name: Test
      run: |
        go test ./...
        .\output\velociraptor.exe golden .\artifacts\testdata\windows\ --env srcDir=./
