name: Windows Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
        echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Use Node.js v12
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - uses: c-hive/gha-npm-cache@v1
    - name: npm install gui
      run: |
            cd gui/static
            npm install
            node node_modules/gulp/bin/gulp.js compile
            cd ../..

    - name: Build
      env:
        CC: x86_64-w64-mingw32-gcc
      run: |
        go run make.go -v Windows

    - name: Test
      run: |
        output\velociraptor.exe golden ./artifacts/testdata/windows/ --env srcDir=./
        go test -v ./...
